version: "3"

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=${Sa_Password:-password123}
      - MSSQL_PID=Developer
    ports:
      - 1433:1433
    volumes:
      - sqlserver_data:/var/opt/mssql
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P ${Sa_Password:-password123} -Q 'SELECT 1' || exit 1"]
      interval: 10s
      retries: 10
      start_period: 10s
      timeout: 3s
  
  mongo:
    image: 'mongo'
    ports:
      - '27017:27017'
    volumes:
      - 'mongo:/data/db'

  kafka-ui:
    container_name: kafka-ui
    image: provectuslabs/kafka-ui:latest
    ports:
      - 8080:8080
    depends_on:
      - zookeeper
      - kafka
      #- schemaregistry
      #- kafka-connect
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9094
      KAFKA_CLUSTERS_0_ZOOKEEPER: zookeeper:2181
      #KAFKA_CLUSTERS_0_JMXPORT: 9997
      #KAFKA_CLUSTERS_0_SCHEMAREGISTRY: http://schemaregistry:8085
      #KAFKA_CLUSTERS_0_KAFKACONNECT_0_NAME: first
      #KAFKA_CLUSTERS_0_KAFKACONNECT_0_ADDRESS: http://kafka-connect:8083

  zookeeper:
    image: confluentinc/cp-zookeeper:5.2.4
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 2181:2181

  kafka:
    image: bitnami/kafka:3.3.1-debian-11-r1
    hostname: kafka1    
    container_name: kafka1
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
    environment:
      ALLOW_PLAINTEXT_LISTENER: "yes"
      BITNAMI_DEBUG: "false"
      KAFKA_CFG_LISTENERS : PLAINTEXT://:9094,CONTROLLER://:9093,EXTERNAL://:9092
      KAFKA_CFG_ADVERTISED_LISTENERS : PLAINTEXT://kafka:9094,EXTERNAL://localhost:9092
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP : CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_CFG_ALLOW_EVERYONE_IF_NO_ACL_FOUND : "true"
      #KAFKA_CFG_AUTHORIZER_CLASS_NAME :
      KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE : "true"
      KAFKA_CFG_DEFAULT_REPLICATION_FACTOR : 1
      KAFKA_CFG_DELETE_TOPIC_ENABLE : "false"
      KAFKA_CFG_LOG_DIRS : /bitnami/kafka/data
      KAFKA_CFG_LOG_FLUSH_INTERVAL_MESSAGES : 10000
      KAFKA_CFG_LOG_FLUSH_INTERVAL_MS : 1000
      KAFKA_CFG_LOG_RETENTION_BYTES : 1073741824
      KAFKA_CFG_LOG_RETENTION_CHECK_INTERVAL_MS : 300000
      KAFKA_CFG_LOG_RETENTION_HOURS : 168
      KAFKA_CFG_LOG_SEGMENT_BYTES : 1073741824
      KAFKA_CFG_MESSAGE_MAX_BYTES : 10485880
      KAFKA_CFG_REPLICA_FETCH_MAX_BYTES: 10485880
      KAFKA_CFG_NUM_IO_THREADS : 8
      KAFKA_CFG_NUM_NETWORK_THREADS : 3
      KAFKA_CFG_NUM_PARTITIONS : 1
      KAFKA_CFG_NUM_RECOVERY_THREADS_PER_DATA_DIR : 1
      KAFKA_CFG_OFFSETS_TOPIC_REPLICATION_FACTOR : 1
      KAFKA_CFG_SOCKET_RECEIVE_BUFFER_BYTES : 102400
      KAFKA_CFG_SOCKET_REQUEST_MAX_BYTES : 104857600
      KAFKA_CFG_SOCKET_SEND_BUFFER_BYTES : 102400
      KAFKA_CFG_SUPER_USERS : User:admin
      KAFKA_CFG_TRANSACTION_STATE_LOG_MIN_ISR : 1
      KAFKA_CFG_TRANSACTION_STATE_LOG_REPLICATION_FACTOR : 1
      KAFKA_CFG_ZOOKEEPER_CONNECT : zookeeper:2181
      KAFKA_CFG_ZOOKEEPER_CONNECTION_TIMEOUT_MS : 6000
      KAFKA_HEAP_OPTS : -Xmx1024m -Xms1024m
      #KAFKA_INTER_BROKER_LISTENER_NAME : INTERNAL
      KAFKA_LOG_DIR : /opt/bitnami/kafka/logs
      KAFKA_VOLUME_DIR : /bitnami/kafka
      KAFKA_ZOOKEEPER_PROTOCOL : PLAINTEXT
volumes:
  mongo:
  sqlserver_data:  